export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      master_tenants: {
        Row: {
          id: string;
          slug: string;
          name: string;
          subscription_tier: string;
          max_users: number;
          max_patients: number;
          max_procedures_per_month: number;
          created_at: string;
          updated_at: string;
          settings: Json;
          currency: string | null;
          is_active: boolean;
          currency_subunit: number | null;
          timezone: string | null;
          license_key: string | null;
          trial_started_at: string | null;
          max_devices: number;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          subscription_tier?: string;
          max_users?: number;
          max_patients?: number;
          max_procedures_per_month?: number;
          created_at?: string;
          updated_at?: string;
          settings?: Json;
          currency?: string | null;
          is_active?: boolean;
          currency_subunit?: number | null;
          timezone?: string | null;
          license_key?: string | null;
          trial_started_at?: string | null;
          max_devices?: number;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          subscription_tier?: string;
          max_users?: number;
          max_patients?: number;
          max_procedures_per_month?: number;
          created_at?: string;
          updated_at?: string;
          settings?: Json;
          currency?: string | null;
          is_active?: boolean;
          currency_subunit?: number | null;
          timezone?: string | null;
          license_key?: string | null;
          trial_started_at?: string | null;
          max_devices?: number;
        };
      };
      clinic_patients: {
        Row: {
          id: string;
          tenant_id: string;
          mrn: string;
          full_name: string;
          phone: string | null;
          email: string | null;
          date_of_birth: string | null;
          gender: string | null;
          address: string | null;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          medical_history_notes: string | null;
          allergies: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          first_name: string | null;
          father_name: string | null;
          last_name: string | null;
          first_name_ar: string | null;
          father_name_ar: string | null;
          last_name_ar: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          mrn: string;
          full_name: string;
          phone?: string | null;
          email?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          address?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          medical_history_notes?: string | null;
          allergies?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          first_name?: string | null;
          father_name?: string | null;
          last_name?: string | null;
          first_name_ar?: string | null;
          father_name_ar?: string | null;
          last_name_ar?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          mrn?: string;
          full_name?: string;
          phone?: string | null;
          email?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          address?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          medical_history_notes?: string | null;
          allergies?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          first_name?: string | null;
          father_name?: string | null;
          last_name?: string | null;
          first_name_ar?: string | null;
          father_name_ar?: string | null;
          last_name_ar?: string | null;
        };
      };
      clinic_visit_sessions: {
        Row: {
          id: string;
          tenant_id: string;
          patient_id: string;
          agenda_event_id: string | null;
          scheduled_start: string | null;
          scheduled_end: string | null;
          actual_check_in: string | null;
          actual_start: string | null;
          actual_end: string | null;
          actual_check_out: string | null;
          session_status: string;
          check_in_method: string | null;
          check_out_method: string | null;
          primary_doctor_id: string | null;
          assigned_room_id: string | null;
          procedure_id: string | null;
          wait_time_minutes: number | null;
          service_time_minutes: number | null;
          total_time_minutes: number | null;
          base_charge_subunits: number | null;
          additional_charges_subunits: number | null;
          discount_subunits: number | null;
          total_charge_subunits: number | null;
          payment_status: string;
          patient_satisfaction_score: number | null;
          patient_feedback: string | null;
          doctor_notes: string | null;
          diagnosis: string | null;
          treatment_performed: string | null;
          follow_up_required: boolean | null;
          follow_up_date: string | null;
          is_abandoned: boolean | null;
          abandoned_at: string | null;
          abandonment_reason: string | null;
          session_metadata: Json;
          created_at: string;
          updated_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          patient_id: string;
          agenda_event_id?: string | null;
          scheduled_start?: string | null;
          scheduled_end?: string | null;
          actual_check_in?: string | null;
          actual_start?: string | null;
          actual_end?: string | null;
          actual_check_out?: string | null;
          session_status?: string;
          check_in_method?: string | null;
          check_out_method?: string | null;
          primary_doctor_id?: string | null;
          assigned_room_id?: string | null;
          procedure_id?: string | null;
          wait_time_minutes?: number | null;
          service_time_minutes?: number | null;
          total_time_minutes?: number | null;
          base_charge_subunits?: number | null;
          additional_charges_subunits?: number | null;
          discount_subunits?: number | null;
          total_charge_subunits?: number | null;
          payment_status?: string;
          patient_satisfaction_score?: number | null;
          patient_feedback?: string | null;
          doctor_notes?: string | null;
          diagnosis?: string | null;
          treatment_performed?: string | null;
          follow_up_required?: boolean | null;
          follow_up_date?: string | null;
          is_abandoned?: boolean | null;
          abandoned_at?: string | null;
          abandonment_reason?: string | null;
          session_metadata?: Json;
          created_at?: string;
          updated_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          patient_id?: string;
          agenda_event_id?: string | null;
          scheduled_start?: string | null;
          scheduled_end?: string | null;
          actual_check_in?: string | null;
          actual_start?: string | null;
          actual_end?: string | null;
          actual_check_out?: string | null;
          session_status?: string;
          check_in_method?: string | null;
          check_out_method?: string | null;
          primary_doctor_id?: string | null;
          assigned_room_id?: string | null;
          procedure_id?: string | null;
          wait_time_minutes?: number | null;
          service_time_minutes?: number | null;
          total_time_minutes?: number | null;
          base_charge_subunits?: number | null;
          additional_charges_subunits?: number | null;
          discount_subunits?: number | null;
          total_charge_subunits?: number | null;
          payment_status?: string;
          patient_satisfaction_score?: number | null;
          patient_feedback?: string | null;
          doctor_notes?: string | null;
          diagnosis?: string | null;
          treatment_performed?: string | null;
          follow_up_required?: boolean | null;
          follow_up_date?: string | null;
          is_abandoned?: boolean | null;
          abandoned_at?: string | null;
          abandonment_reason?: string | null;
          session_metadata?: Json;
          created_at?: string;
          updated_at?: string;
          completed_at?: string | null;
        };
      };
      clinic_invoices: {
        Row: {
          id: string;
          tenant_id: string;
          session_id: string;
          patient_id: string;
          invoice_number: string;
          subtotal_subunits: number;
          tax_subunits: number;
          discount_subunits: number;
          total_subunits: number;
          paid_subunits: number;
          balance_subunits: number;
          status: string;
          issued_at: string | null;
          due_at: string | null;
          paid_at: string | null;
          cancelled_at: string | null;
          payment_method: string | null;
          payment_reference: string | null;
          notes: string | null;
          invoice_metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          session_id: string;
          patient_id: string;
          invoice_number: string;
          subtotal_subunits: number;
          tax_subunits?: number;
          discount_subunits?: number;
          total_subunits: number;
          paid_subunits?: number;
          balance_subunits: number;
          status?: string;
          issued_at?: string | null;
          due_at?: string | null;
          paid_at?: string | null;
          cancelled_at?: string | null;
          payment_method?: string | null;
          payment_reference?: string | null;
          notes?: string | null;
          invoice_metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          session_id?: string;
          patient_id?: string;
          invoice_number?: string;
          subtotal_subunits?: number;
          tax_subunits?: number;
          discount_subunits?: number;
          total_subunits?: number;
          paid_subunits?: number;
          balance_subunits?: number;
          status?: string;
          issued_at?: string | null;
          due_at?: string | null;
          paid_at?: string | null;
          cancelled_at?: string | null;
          payment_method?: string | null;
          payment_reference?: string | null;
          notes?: string | null;
          invoice_metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      clinic_users: {
        Row: {
          id: string;
          tenant_id: string;
          email: string;
          full_name: string;
          role: string;
          is_active: boolean;
          last_login_at: string | null;
          created_at: string;
          updated_at: string;
          pin_code: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          email: string;
          full_name: string;
          role?: string;
          is_active?: boolean;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
          pin_code?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          email?: string;
          full_name?: string;
          role?: string;
          is_active?: boolean;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
          pin_code?: string | null;
        };
      };
      clinic_rooms: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          room_type: string | null;
          capacity: number | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          room_type?: string | null;
          capacity?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          name?: string;
          room_type?: string | null;
          capacity?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
